# Generated by Django 3.0 on 2020-01-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basic', '0002_auto_20200114_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
